# Generated by Django 5.0.2 on 2024-04-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_homework'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='description',
            field=models.CharField(default='enter', max_length=50),
        ),
    ]
