# Generated by Django 5.0.2 on 2024-04-05 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_todo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='titile',
        ),
        migrations.AddField(
            model_name='todo',
            name='title',
            field=models.CharField(default='enter', max_length=30),
        ),
    ]
